In [11]:
import numpy as np

In [8]:
a=pd=.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
print(c.ndim)

3


In [16]:
print(c.shape)

(2, 2, 2)


In [17]:
print(c.shape)

(2, 2, 2)


In [19]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [22]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [27]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#BASIC DATA TYPES

In [31]:
a=np.arange(10)
print(a.dtype)

int64


In [38]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [39]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


#OTHER DATATYPES

In [51]:
import numpy as np

a = np.array(['pavam', 'mani'])
print(a.dtype)


<U5


#COPIES AND VIEWING

In [56]:
import numpy as np
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
